### ISSUE TITLE
Feature request: required tag

### ISSUE THREAD

**Issue by FabHof** [omeid/uconfig#10]
I would like a plugin that makes sure that fields with a `required` tag are present.

**Comment by omeid** [comment]
You're lucky because @joncfoo had already started some work on this. Please try the #required-plugin branch and let me know if you're happy with it.

It uses Go's very own `.IsZero` from `reflect` which means it doesn't work well with `empty values`, unfort.

**Comment by omeid** [comment]
I am going to close this in favor of #11. If you're still interested, please let me know and we can land #11.
