### ISSUE TITLE
Can we not expose the FIELD column in the help document?

### ISSUE THREAD

**Issue by kant777** [omeid/uconfig#13]
Can we not expose the `FIELD` column in the help document? Although the below looks good I don't think its a good idea to reveal how the conf is mapped to an internal data structure. I don't see any configuration library doing that however will leave it to the maintainer 

```
Supported Fields:
FIELD                FLAG                  ENV                  DEFAULT                      USAGE
-----                -----                 -----                -------                      -----
Hosts                -hosts                HOSTS                localhost,localhost.local    the ip or domains to bind to
Redis.Address        -redis-address        REDIS_ADDRESS        redis-master                 
Redis.Port           -redis-port           REDIS_PORT           6379                         
Redis.Password       -redis-password       REDIS_PASSWORD                                    
Redis.DB             -redis-db             REDIS_DB             0                            
Redis.Expire         -redis-expire         REDIS_EXPIRE         5s                           
Database.Address     -database-address     DATABASE_ADDRESS     localhost                    
Database.Port        -database-port        DATABASE_PORT        28015                        
Database.Database    -database-database    DATABASE_DATABASE    my-project    

```

**Comment by omeid** [comment]
Hello Kant777,

One of the objectives of uConfig is to make configuration discoverable and self-documented.

The "Field" is essentially the _Canonical_ name for every user configurable option of the program.

Considering that there exists a mechanism for a struct to specify a _static_[^1] field name for a given property, configurations like the one below is not only possible but unfort common for compatibility reasons.

However, without the _Field_ tag it is much harder to understand what each flag or env var is for.


```
Supported Fields:
FIELD                      FLAG                  ENV             DEFAULT                      USAGE
-----                      -----                 -----           -------                      -----
Hosts                      -hosts                HOSTS           localhost,localhost.local    the ip or domains to bind to
Redis.Address              -cache-address        CACHE_ADDRESS   redis-master
Blob.Address               -cache-host           CACHE_HOST      blob-v1
Database.Address           -backup-host          DB_MAIN         localhost                    
Database.AltAddress        -secondary-host       DB_SECONDARY    localhost                    
```

It can certainly be argued that these are poor flag and env var choices, or even that this is a diabolical example.

But the point remains, the Field name provides clarity for _static_ and ambiguous configuration options, and even help find conflicts.


I hope this is helpful.



[^1]:In contrast to dynamically generated names based on the overall structure of the configuration, as per the uConfigs default.

**Comment by kant777** [comment]
The problem I am facing is this. I usually like to just do `myapp -h` and paste the help doc as a user facing document however I don't really want to let the users know on how they are mapped to my internal structures of the program. Thats really the only reason I am requesting this. 

if we remove the field column(don't want to call it as tag to avoid confusion with struct tags) then we can display the help document in horizontal fashion rather than vertical split of columns.

Again, I am not saying anything wrong with the current approach or formatting. As a matter of fact it is beautiful. I just don't want to expose the source code data structures or fields to the end users.

**Comment by omeid** [comment]
I und

**Comment by omeid** [comment]
I am not sure I understand your concern, specially the vertical columns layout. Can you please provide an example of how you would expect the output?

To illustrate my point about why the Field is useful, consider the same example in my previous comment without the field column, could you tell what is for what?

```


Supported Fields:
FLAG                  ENV             DEFAULT                      USAGE
-----                 -----           -------                      -----
-hosts                HOSTS           localhost,localhost.local    the ip or domains to bind to
-cache-address        CACHE_ADDRESS   redis-master
-cache-host           CACHE_HOST      blob-v1
-backup-host          DB_MAIN         localhost                    
-secondary-host       DB_SECONDARY    localhost     
```
