### ISSUE TITLE
unknown revision v1.2.0

### ISSUE THREAD

**Issue by srt0422** [omeid/uconfig#15]
My golang project fails to build as a result of an unknown revision of uconfig.

I have this in my go.mod require list: `github.com/omeid/uconfig v1.2.0`

Here are my terminal commands and output: 
![Screenshot 2023-10-04 at 10 19 30 AM](https://github.com/omeid/uconfig/assets/869171/48c7cc2f-588e-4531-9445-66908b2cd44b)

I'm using golang version 1.19.4 darwin/amd64

I see here [https://pkg.go.dev/github.com/omeid/uconfig/plugins](https://pkg.go.dev/github.com/omeid/uconfig/plugins) that you have the module registered under the version v1.2.0, but your tags in the repo do not match:  
![Screenshot 2023-10-04 at 11 08 46 AM](https://github.com/omeid/uconfig/assets/869171/1bb505f4-a03c-4fe7-9067-29ab78f48d39)

I think this is the source of the problem.

As a workaround, I've forked the repo and replaced the path with my forked repo like so: `replace github.com/omeid/uconfig => github.com/Lumerin-protocol/uconfig v0.0.5` 

My team isn't happy with the workaround, so I'm just wondering if you could add a matching tag for v1.2.0.   I think that would solve the problem.  or register the package under v0.0.4, and please create a matching tag.

**Comment by omeid** [comment]
Hello @srt0422 

Try github.com/omeid/uconfig@v0.5.0

Thanks

**Comment by srt0422** [comment]
that worked!!! thank you
