### ISSUE TITLE
How to use the tag `default:""` for [ ]string?

### ISSUE THREAD

**Issue by victormn** [omeid/uconfig#4]
```
type Config struct {
  Ports    []string `default:""`
}
```

I need to set up a list of strings as default value for "Ports". How can I do this?

Thanks

**Comment by omeid** [comment]
Hello @victormn,

Unfort string or slices in general are not supported yet.

Contributions are welcome and I will be more than happy to review and help you, the relevant part is [here](https://github.com/omeid/uconfig/blob/master/flat/field.go#L72), I think we could add a comma separated list so you can do `default:"valueA,valueB,valueC"` and so forth.

**Comment by omeid** [comment]
@victormn You could use an a slice that implements the `encoding.TextUnmarshaller`. If you have problem implementing this, I am happy to add some documentation on how to do it.
